export const itemStatuses = [
  { label: 'stripes-inventory-components.item.status.agedToLost', value: 'Aged to lost' },
  { label: 'stripes-inventory-components.item.status.available', value: 'Available' },
  { label: 'stripes-inventory-components.item.status.awaitingPickup', value: 'Awaiting pickup' },
  { label: 'stripes-inventory-components.item.status.awaitingDelivery', value: 'Awaiting delivery' },
  { label: 'stripes-inventory-components.item.status.checkedOut', value: 'Checked out' },
  { label: 'stripes-inventory-components.item.status.claimedReturned', value: 'Claimed returned' },
  { label: 'stripes-inventory-components.item.status.declaredLost', value: 'Declared lost' },
  { label: 'stripes-inventory-components.item.status.inProcess', value: 'In process' },
  { label: 'stripes-inventory-components.item.status.inProcessNonRequestable', value: 'In process (non-requestable)' },
  { label: 'stripes-inventory-components.item.status.inTransit', value: 'In transit' },
  { label: 'stripes-inventory-components.item.status.intellectualItem', value: 'Intellectual item' },
  { label: 'stripes-inventory-components.item.status.longMissing', value: 'Long missing' },
  { label: 'stripes-inventory-components.item.status.lostAndPaid', value: 'Lost and paid' },
  { label: 'stripes-inventory-components.item.status.missing', value: 'Missing' },
  { label: 'stripes-inventory-components.item.status.onOrder', value: 'On order' },
  { label: 'stripes-inventory-components.item.status.orderClosed', value: 'Order closed' },
  { label: 'stripes-inventory-components.item.status.paged', value: 'Paged' },
  { label: 'stripes-inventory-components.item.status.restricted', value: 'Restricted' },
  { label: 'stripes-inventory-components.item.status.unavailable', value: 'Unavailable' },
  { label: 'stripes-inventory-components.item.status.unknown', value: 'Unknown' },
  { label: 'stripes-inventory-components.item.status.withdrawn', value: 'Withdrawn' },
];
